name: Docker CI with Quality Gates and Python E2E Tests

on:
  push:
    branches: [ "main" ]

jobs:
  quality-gates:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format:check

  unit-tests:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest
    needs: quality-gates
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  install-chrome:
    name: Install Chrome
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
  
  e2e-tests-python:
    name: Clone Python Repo & Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone External Python Repo
        run: git clone https://github.com/Daniel1309CHC/CampusPartyAutomationTest.git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create Virtual Environment
        run: |
          cd e2e-tests-python
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          cd e2e-tests-python
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run E2E Tests (Selenium, PyTest, etc.)
        run: |
          cd e2e-tests-python
          source venv/bin/activate
          python runnert.py --browser chrome --headless --report

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: e2e-tests-python
    if: success()  # Solo ejecuta si todo lo anterior pasó
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t my-image-name:latest .

      - name: Tag and Push to Docker Hub
        run: |
          docker tag my-image-name:latest ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
